export const movieList = [
  {
    title: "Baby Driver",
    year: "2017",
    time: "1h 53m",
    genre: ["Action", "Adventure", "Crime"],
    poster: "/assets/films/baby-driver.png",
  },
  {
    title: "Squid Game",
    year: "2017",
    time: "1 Season",
    genre: ["Drama", "Crime", "Action"],
    poster: "/assets/films/squid-game.png",
  },
  {
    title: "Titans",
    year: "2018",
    time: "4 Seasons",
    genre: ["Action", "Crime", "Fantasy", "Animation"],
    poster: "/assets/films/titans.png",
  },
  {
    title: "Wednesday",
    year: "2022",
    time: "1 Season",
    genre: ["Drama", "Comedy"],
    poster: "/assets/films/wednesday.png",
  },
  {
    title: "The Witcher",
    year: "2019",
    time: "2 Seasons",
    genre: ["Action", "Family", "Adventure"],
    poster: "/assets/films/witcher.png",
  },
  {
    title: "1899",
    year: "2022",
    time: "1 Season",
    genre: ["documentary", "Family", "Crime"],
    poster: "/assets/films/1899.png",
  },
];

export const movieAll = [
  {
    title: "Baby Driver",
    year: "2017",
    time: "1h 53m",
    genre: ["Action", "Adventure", "Crime"],
    poster: "/assets/films/baby-driver.png",
  },
  {
    title: "Squid Game",
    year: "2017",
    time: "1 Season",
    genre: ["Drama", "Crime", "Action"],
    poster: "/assets/films/squid-game.png",
  },
  {
    title: "Titans",
    year: "2018",
    time: "4 Seasons",
    genre: ["Action", "Crime", "Fantasy", "Animation"],
    poster: "/assets/films/titans.png",
  },
  {
    title: "Wednesday",
    year: "2022",
    time: "1 Season",
    genre: ["Drama", "Comedy"],
    poster: "/assets/films/wednesday.png",
  },
  {
    title: "The Witcher",
    year: "2019",
    time: "2 Seasons",
    genre: ["Action", "Family", "Adventure"],
    poster: "/assets/films/witcher.png",
  },
  {
    title: "1899",
    year: "2022",
    time: "1 Season",
    genre: ["documentary", "Family", "Crime"],
    poster: "/assets/films/1899.png",
  },
  {
    title: "Baby Driver",
    year: "2017",
    time: "1h 53m",
    genre: ["Action", "Adventure", "Crime"],
    poster: "/assets/films/baby-driver.png",
  },
  {
    title: "Squid Game",
    year: "2017",
    time: "1 Season",
    genre: ["Drama", "Crime", "Action"],
    poster: "/assets/films/squid-game.png",
  },
  {
    title: "Titans",
    year: "2018",
    time: "4 Seasons",
    genre: ["Action", "Crime", "Fantasy", "Animation"],
    poster: "/assets/films/titans.png",
  },
  {
    title: "Wednesday",
    year: "2022",
    time: "1 Season",
    genre: ["Drama", "Comedy"],
    poster: "/assets/films/wednesday.png",
  },
  {
    title: "The Witcher",
    year: "2019",
    time: "2 Seasons",
    genre: ["Action", "Family", "Adventure"],
    poster: "/assets/films/witcher.png",
  },
  {
    title: "1899",
    year: "2022",
    time: "1 Season",
    genre: ["documentary", "Family", "Crime"],
    poster: "/assets/films/1899.png",
  },
  {
    title: "Baby Driver",
    year: "2017",
    time: "1h 53m",
    genre: ["Action", "Adventure", "Crime"],
    poster: "/assets/films/baby-driver.png",
  },
  {
    title: "Squid Game",
    year: "2017",
    time: "1 Season",
    genre: ["Drama", "Crime", "Action"],
    poster: "/assets/films/squid-game.png",
  },
  {
    title: "Titans",
    year: "2018",
    time: "4 Seasons",
    genre: ["Action", "Crime", "Fantasy", "Animation"],
    poster: "/assets/films/titans.png",
  },
  {
    title: "Wednesday",
    year: "2022",
    time: "1 Season",
    genre: ["Drama", "Comedy"],
    poster: "/assets/films/wednesday.png",
  },
  {
    title: "The Witcher",
    year: "2019",
    time: "2 Seasons",
    genre: ["Action", "Family", "Adventure"],
    poster: "/assets/films/witcher.png",
  },
  {
    title: "1899",
    year: "2022",
    time: "1 Season",
    genre: ["documentary", "Family", "Crime"],
    poster: "/assets/films/1899.png",
  },
];

export const genre = [
  "Action",
  "Adventure",
  "Animation",
  "Comedy",
  "Crime",
  "Drama",
  "Family",
  "Fantasy",
];

export const actress = [
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
  {
    name: "Milly Bobby Brown",
    actressName: "Jane Hopper",
    image: "/assets/films/actress.png",
  },
];
